name: 'Verify and Preview'

on:
  pull_request:
    branches:
      - next

permissions:
  pull-requests: read

jobs:
  chromatic:
    # TODO update branch
    uses: trendyol/baklava-icons/.github/workflows/publish-chromatic.yml@feature/storybook
