name: 'Verify and Preview'

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: read

jobs:
  chromatic:
    uses: trendyol/baklava-icons/.github/workflows/publish-chromatic.yml@main
