name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write
  pages: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  storybook:
    name: Publish Storybook
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: "pages"
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Node env
        uses: actions/setup-node@v6
        with:
          node-version: '24.10.0'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Build Storybook
        run: npm run build-storybook
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './storybook-static/.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: storybook
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set Node env
        uses: actions/setup-node@v6
        with:
          node-version: '24.10.0'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm clean-install
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Run build
        run: npm run build
      - name: Release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  chromatic:
    name: Publish Chromatic
    runs-on: ubuntu-latest
    if: github.repository == 'Trendyol/baklava-icons'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set Node env
        uses: actions/setup-node@v6
        with:
          node-version: '24.10.0'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: chpt_4ce7e3f28a30111
